### ISSUE TITLE
Melbourne channels 10, Bold, Peach, Shake missing?

### ISSUE THREAD

**Issue by Cloudman999** [matthuisman/new.mjh.nz#1]
Hi @matthuisman 
Enjoying your Melbourne IPTV streams. I noticed that channels 10, Bold, Peach, and Shake do not appear. Are they not available?

Thank you Matt
Regards
@Cloudman

**Comment by Cloudman999** [comment]
> What urls are you using? If your actually using these new urls, they are not complete yet. I.mjh.nz have them, but not as good epg
> 
Hi Matt

I am using the following...
https://github.com/matthuisman/new.mjh.nz/raw/master/au/melbourne/playlist.m3u8

https://github.com/matthuisman/new.mjh.nz/raw/master/au/melbourne/epg.xml.gz

... so you are saying the channel 10, Bold, Peach are not included.

Are you planning to add them?

Regards
@Cloudman999

**Comment by matthuisman** [comment]
yes, these files are very "work in progress".
Best to use the files from i.mjh.nz in the meantime

**Comment by Cloudman999** [comment]
Ok then. Will do @matthuisman 
Thank you for everything you do for us with all your fantastic add-ons and streams. It is very much appreciated!

Please close this issue.
Kindest regards
@Cloudman999
